/**
 * Every user-visible string lives here (English, per approved plan).
 * No i18n framework in MVP — centralization only.
 */
export const strings = {
  common: {
    appName: 'ApexFOSS',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    add: 'Add',
    back: 'Back',
    none: 'None',
    optional: 'optional',
    loading: 'Loading…',
    retry: 'Retry',
    saving: 'Saving…',
    error: 'Something went wrong',
    create: 'Create',
    search: 'Search',
    noMatches: 'No matches',
    confirmDelete: 'Delete this item?',
    discardChanges: 'Discard unsaved changes?',
    discard: 'Discard',
    keepEditing: 'Keep editing',
  },
  tabs: {
    home: 'Home',
    routines: 'Routines',
    history: 'History',
    settings: 'Settings',
  },
  home: {
    title: 'ApexFOSS',
    tagline: 'Local-first workout engine',
    startWorkout: 'Start workout',
    activeSession: 'Active session',
    resume: 'Resume',
    recentSessions: 'Recent sessions',
    noSessions: 'No sessions yet. Create a routine and start training.',
    exercises: 'Exercises',
    routines: 'Routines',
    authoring: 'Authoring',
    training: 'Training',
    today: 'Today',
    weekSection: 'This week',
    weekSessions: 'Sessions',
    weekVolume: 'Volume',
    weekTime: 'Time',
    weekTimeUnit: 'min',
    chartCaption: 'Daily volume · kg·reps',
    chartEmpty: 'Complete a session to see your daily load here.',
    currentRoutine: 'Current routine',
    lastTrained: 'Last trained',
    recent: 'Recent training',
    recentEmptyTitle: 'No training history yet',
    recentEmptyBody: 'Completed sessions appear here with duration, sets and volume.',
    tools: 'Quick tools',
    appSection: 'App',
  },
  exercises: {
    title: 'Exercises',
    search: 'Search exercises…',
    newExercise: 'New exercise',
    editTitle: 'Edit exercise',
    name: 'Name',
    nameRequired: 'Name is required',
    namePlaceholder: 'e.g. Back Squat',
    category: 'Category',
    categoryPlaceholder: 'e.g. legs',
    equipment: 'Equipment',
    equipmentPlaceholder: 'e.g. barbell',
    metrics: 'Tracked metrics',
    metricWeight: 'Weight',
    metricReps: 'Reps',
    metricDuration: 'Duration',
    metricDistance: 'Distance',
    empty: 'No exercises yet.',
    emptyAction: 'Create exercise',
    deleteConfirm: 'Delete this exercise?',
    deleteInUse: 'Exercise is referenced by routines. Delete anyway?',
    selectTitle: 'Select exercise',
    selectEmpty: 'No exercises yet. Create one from the Exercises screen.',
  },
  routines: {
    title: 'Routines',
    newRoutine: 'New routine',
    editTitle: 'Routine',
    name: 'Routine name',
    nameRequired: 'Routine name is required',
    empty: 'No routines yet.',
    emptyAction: 'Create routine',
    deleteConfirm: 'Delete this routine?',
    start: 'Start',
    blocks: 'Blocks',
    newBlock: 'Add block',
    deleteBlock: 'Delete this block and its steps?',
    deleteStep: 'Delete this step?',
    noSteps: 'No steps yet',
    blockName: 'Block name',
    untitledRoutine: 'Untitled routine',
    saveFailed: 'Could not save routine',
    blockKind: {
      normal: 'NORMAL',
      superset: 'SUPERSET',
      contrast: 'CONTRAST',
      circuit: 'CIRCUIT',
      interval: 'INTERVAL',
    },
    rounds: 'Rounds',
    kind: 'Kind',
    steps: 'Steps',
    step: 'Step',
    addStep: 'Add step',
    exercise: 'Exercise',
    selectExercise: 'Select exercise',
    prescription: {
      title: 'Prescription',
      sets: 'Sets',
      reps: 'Reps',
      repsMin: 'Reps min',
      repsMax: 'Reps max',
      weight: 'Weight (kg)',
      duration: 'Duration (s)',
      rir: 'RIR',
      tempo: 'Tempo',
      tempoEcc: 'Ecc (s)',
      tempoPauseBottom: 'Pause bottom (s)',
      tempoCon: 'Con (s)',
      tempoPauseTop: 'Pause top (s)',
    },
    transition: {
      title: 'After this step',
      nextStep: 'Next step',
      loop: 'Loop to first step',
      nextBlock: 'Next block',
      immediate: 'IMMEDIATE',
      rest: 'REST',
      auto: 'AUTO_ADVANCE',
      delaySeconds: 'Rest (s)',
    },
  },
  workout: {
    start: 'Start workout',
    completeSet: 'COMPLETE',
    skip: 'Skip',
    undo: 'Undo',
    finish: 'Finish workout',
    set: 'Set',
    of: 'of',
    round: 'Round',
    next: 'NEXT',
    rest: 'REST',
    skipRest: 'Skip rest',
    previous: 'Previous',
    noPrevious: 'First time',
    weight: 'kg',
    reps: 'reps',
    duration: 'time',
    distance: 'm',
    rir: 'RIR',
    sessionSaved: 'Session saved',
    discard: 'Discard session',
    discardConfirm: 'Discard this session? Logged sets will be deleted.',
    finishConfirm: 'Finish and save this session?',
    activeConflict: 'An active session exists. Discard it and start a new one?',
    loadFailed: 'Could not load workout',
    emptyRoutine: 'This routine has no steps',
    startFailed: 'Could not start workout',
    block: 'Block',
    target: 'Target',
    tempo: 'Tempo',
    actual: 'Actual',
    plannedSets: 'planned sets',
    pause: 'Pause',
    resume: 'Resume',
    paused: 'Paused',
    nextUp: 'Next up',
    summary: 'Session summary',
    setsCompleted: 'Sets',
    note: 'Session note',
    notePlaceholder: 'How did it feel? Numbers, cues, PRs…',
    noteSaved: 'Note saved',
  },
  timer: {
    rest: 'REST',
    autoAdvance: 'AUTO',
  },
  history: {
    title: 'History',
    empty: 'No sessions yet',
    emptyDetail: 'Completed workouts will appear here.',
    detail: 'Session',
    detailMissing: 'Session not found',
    completed: 'Completed',
    completedAt: 'Completed',
    duration: 'Duration',
    volume: 'Volume',
    sets: 'Sets',
    actualPerformed: 'Actual',
    notLogged: 'Not logged',
    sessionLoad: 'Session load',
    resistanceLoad: 'Resistance',
    durationWork: 'Duration work',
    compare: 'Compare with previous',
  },
  integrity: {
    title: 'Routine checks',
    ok: 'No problems found.',
    error: 'Error',
    warning: 'Warning',
    messages: {
      empty_routine: 'Routine has no blocks or steps.',
      no_work_steps: 'No work sets — the routine would finish without training work.',
      invalid_rounds: 'Block rounds must be at least 1.',
      missing_interval_spec: 'Interval block is missing valid work/rest/rounds settings.',
      orphan_transition: 'A transition points to a step that does not exist.',
      transition_cycle: 'Transitions form a loop that may never finish.',
      zero_target_sets: 'Work step has no target set count (engine assumes 1 set).',
      duplicate_step_id: 'Two steps in this block share the same id.',
    },
  },
  preview: {
    title: 'Routine preview',
    open: 'Preview',
    workSets: 'Work sets',
    plannedRest: 'Planned rest',
    minutes: 'min',
    blocks: 'Blocks',
    exercises: 'Exercises',
    byExercise: 'Sets by exercise',
    setsUnit: 'sets',
    how: 'Simulated step by step with the same engine that runs workouts.',
    truncated: 'Preview stopped early — the routine may loop indefinitely. Check step transitions.',
    empty: 'Nothing to preview yet — add blocks and steps first.',
  },
  compare: {
    title: 'Compare sessions',
    baseline: 'Previous',
    current: 'Selected',
    noBaseline: 'No earlier session to compare with',
    noBaselineBody: 'Comparison needs at least two completed sessions.',
    totals: 'Totals',
    volume: 'Volume',
    sets: 'Sets',
    time: 'Time',
    previous: 'Previous',
    selected: 'Selected',
    change: 'Change',
    exercises: 'Exercises',
    onlyPrevious: 'Only in previous',
    onlySelected: 'Only in selected',
    bestWeight: 'Best weight',
    bestReps: 'Most reps',
    est1rm: 'Est. 1RM (Epley)',
    noPerExerciseLoad: 'No load in either session',
    kgRepsUnit: 'kg·reps',
    secondsUnit: 's',
  },
  export: {
    title: 'Export',
    csv: 'Export CSV',
    csvHint: 'Sessions and set logs as CSV',
    json: 'Export JSON',
    jsonHint: 'Structured sessions as JSON',
    exported: 'Export ready',
    nothing: 'No completed sessions to export',
  },
  portability: {
    title: 'Portability',
    subtitle: 'Share routines and backup offline',
    exportRoutine: 'Export routine',
    exportRoutineHint: 'Share as portable JSON',
    showQr: 'Show QR',
    qrUnavailable: 'Too large for QR — use Share instead',
    importRoutine: 'Import routine',
    importRoutineHint: 'Paste portable JSON or open a deep link',
    importPasteTitle: 'Paste routine JSON',
    importPreviewTitle: 'Import preview',
    importConfirm: 'Import',
    importDone: 'Routine imported',
    importFailed: 'Import failed',
    createBackup: 'Create backup',
    createBackupHint: 'Full offline backup (.apexbackup JSON)',
    restoreBackup: 'Restore backup',
    restoreBackupHint: 'Paste backup JSON — replaces ALL local data',
    restoreConfirmTitle: 'Restore backup?',
    restoreConfirmBody:
      'This replaces every exercise, routine, session, and log on this device. This cannot be undone.',
    restoreConfirm: 'Restore',
    restoreDone: 'Backup restored',
    restoreFailed: 'Restore failed',
    invalidPayload: 'Invalid or corrupted payload',
    tooLarge: 'Payload too large for QR',
    matchedExercises: 'Matched exercises',
    newExercises: 'New exercises',
    blockCount: 'Blocks',
    stepCount: 'Steps',
    emptyPaste: 'Paste content is empty',
    schemeNote: 'Deep links use apexfoss://import',
  },
  units: {
    kg: 'kg',
    seconds: 's',
    minutes: 'min',
  },
  numpad: {
    title: 'Athlete numpad',
    backspace: '⌫',
    clear: 'Clear',
    active: 'Editing',
    tapField: 'Tap a field to edit',
    modifierPrefix: 'Quick add',
  },
  tempo: {
    title: 'TEMPO',
    start: 'Start tempo',
    cancel: 'Cancel',
    restart: 'Restart',
    complete: 'Tempo complete',
    currentPhase: 'Current phase',
    ready: 'Ready',
    phases: {
      eccentric: 'ECCENTRIC',
      pauseBottom: 'BOTTOM PAUSE',
      concentric: 'CONCENTRIC',
      pauseTop: 'TOP PAUSE',
    },
    phaseDots: {
      eccentric: 'Eccentric',
      pauseBottom: 'Bottom pause',
      concentric: 'Concentric',
      pauseTop: 'Top pause',
    },
  },
  interval: {
    title: 'INTERVAL',
    ready: 'Interval ready',
    start: 'Start interval',
    cancel: 'Cancel',
    restart: 'Restart',
    skipPhase: 'Skip phase',
    finishRound: 'Finish work',
    complete: 'Interval complete',
    continue: 'Continue workout',
    round: 'Round',
    of: 'of',
    next: 'NEXT',
    modes: {
      hiit: 'HIIT',
      emom: 'EMOM',
      glycolytic: 'GLYCOLYTIC',
    },
    phases: {
      prep: 'PREP',
      work: 'WORK',
      rest: 'REST',
    },
    editor: {
      mode: 'Mode',
      work: 'Work (s)',
      rest: 'Rest (s)',
      period: 'Period (s)',
      rounds: 'Rounds',
      prep: 'Prep (s)',
      periodHint: 'EMOM period (e.g. 60)',
      workHint: '0 = full minute',
      summary: 'Summary',
    },
  },
  athleteTools: {
    section: 'Athlete tools',
    load: 'Training load',
    muscles: 'Muscle distribution',
    inventory: 'Load inventory',
    readiness: 'Readiness tap test',
    autoreg: 'RIR autoregulation',
    records: 'Personal records',
  },
  records: {
    title: 'Personal records',
    emptyTitle: 'No records yet',
    emptyBody: 'Records appear after completed sessions with logged sets.',
    weight: 'Best weight',
    reps: 'Most reps',
    est1rm: 'Est. 1RM (Epley)',
    duration: 'Longest set',
    distance: 'Farthest set',
    estimateBadge: 'Estimated',
    estimateHint: 'Estimate: weight × (1 + reps ÷ 30) — not a measured value.',
    history: 'Record history',
    previously: 'Previously',
    showHistory: 'Show history',
    hideHistory: 'Hide history',
    kg: 'kg',
    secUnit: 's',
    mUnit: 'm',
  },
  load: {
    title: 'Training load',
    today: 'Today',
    last7: '7 days',
    last28: '28 days',
    resistance: 'Resistance',
    duration: 'Duration',
    sets: 'Sets',
    noData: 'No completed sessions in this window',
    kgReps: 'kg·reps',
    seconds: 's',
    completedSets: 'Completed sets',
    trends: {
      section: 'Load trends',
      current7: 'Last 7 days',
      previous7: 'Previous 7 days',
      current28: 'Last 28 days',
      previous28: 'Previous 28 days',
      change: 'Change',
      noPrevious: 'No previous data',
      sessions: 'Sessions',
      load: 'Load',
    },
    ratio: {
      label: '7d / 28d load ratio',
      currentWeek: 'Current week',
      baselineWeek: 'Baseline (previous 28 days ÷ 4)',
      noBaseline: 'No baseline sessions in the previous 28 days',
      zeroBaseline: 'Baseline window has no resistance load',
    },
    rhythm: {
      section: 'Training rhythm',
      window: 'Last 7 days',
      frequency: 'Sessions / week',
      avgSets: 'Avg sets / session',
      density: 'Work / minute',
      densityUnit: 'kg·reps/min',
      weekly: 'Weekly volume',
      weeklyLabel: 'Weekly volume, last 8 weeks, kg·reps',
      weeklyCaption: 'Weekly volume · kg·reps · last 8 weeks',
      weeklyEmpty: 'Complete a session to see your weekly volume here.',
    },
  },
  muscles: {
    title: 'Muscle distribution',
    noData: 'No resistance load in this window',
    mappedLoad: 'Mapped load',
    sessions: 'Sessions',
    share: 'Share',
    sets: 'Sets',
    loadLabel: 'Load',
    exercisesLabel: 'Exercises',
    contributing: 'Contributing exercises',
    unmappedFor: 'Muscle data unavailable for',
    exerciseOne: 'exercise',
    exerciseMany: 'exercises',
    detailHint: 'Tap a region to see its detail. Timed work is not included.',
    groups: {
      chest: 'Chest',
      upper_back: 'Upper back',
      lats: 'Lats',
      front_delts: 'Front delts',
      side_delts: 'Side delts',
      rear_delts: 'Rear delts',
      biceps: 'Biceps',
      triceps: 'Triceps',
      forearms: 'Forearms',
      abs: 'Abs',
      obliques: 'Obliques',
      lower_back: 'Lower back',
      glutes: 'Glutes',
      quads: 'Quads',
      hamstrings: 'Hamstrings',
      calves: 'Calves',
      adductors: 'Adductors',
    },
  },
  inventory: {
    title: 'Load inventory',
    target: 'Target (kg)',
    bar: 'Bar (kg)',
    solve: 'Solve',
    status: {
      exact: 'Exact',
      closest: 'Closest',
      impossible: 'Cannot reach target with current inventory',
    },
    achieved: 'Achieved',
    difference: 'Difference',
    items: 'Items',
    addItem: 'Add item',
    name: 'Name',
    weight: 'Weight (kg)',
    quantity: 'Quantity',
    perSide: 'Per side (×2)',
    remove: 'Remove',
    empty: 'No items yet. Add plates or load pieces.',
    noAllocations: 'No allocations needed (target equals bar).',
    summary: 'Result',
    saved: 'Inventory saved on this device.',
    loadFailed: 'Could not load saved inventory.',
    saveFailed: 'Could not save inventory.',
  },
  readiness: {
    title: 'Readiness tap test',
    instructions: 'Tap as fast as you can for 10 seconds.',
    start: 'Start test',
    stop: 'Stop',
    tapping: 'TAP',
    elapsed: 'Elapsed',
    taps: 'Taps',
    score: 'Score',
    baseline: 'Baseline',
    deviation: 'Deviation',
    noBaseline: 'Need at least 3 prior tests before a score is shown.',
    insufficient: 'Not enough history for a baseline yet.',
    samples: 'samples',
    completed: 'Test recorded',
    failed: 'Could not record test',
    history: 'Recent tests',
    scoreUnit: '/100',
  },
  autoreg: {
    title: 'RIR autoregulation',
    enabled: 'Enabled',
    targetRir: 'Target RIR',
    step: 'Step (kg)',
    min: 'Min (kg)',
    max: 'Max (kg)',
    recommendation: 'Next set suggestion',
    hold: 'Hold',
    increase: 'Increase',
    decrease: 'Decrease',
    disabled: 'Autoregulation is off',
    noTarget: 'Set a target RIR in the prescription to enable adjustments.',
    hint: 'Adjustments apply at runtime only — routine definitions are never modified.',
  },
  trust: {
    section: 'App',
    title: 'Trust, Safety & Legal',
    privacy: 'Privacy',
    privacyBody:
      'ApexFOSS stores workouts, routines and settings only on this device. There are no accounts and no project-run servers. Exports and backups only leave the device when you share them yourself. See docs/PRIVACY.md in the repository for the full notice.',
    terms: 'Terms of Use',
    termsBody:
      'Draft pending human/legal review — see docs/TERMS_OF_USE.md. Using this software is your own responsibility; no professional relationship is created by using it.',
    health: 'Health & Fitness',
    healthBody:
      'ApexFOSS is general fitness software for recording and timing your own training. It is not medical software: it does not diagnose, treat, monitor or predict any health condition, and it does not replace professional advice. Physical activity carries risk — train within your own limits.',
    dataStorage: 'Data & Storage',
    dataBody:
      'Everything below lives in the local database on this device. Backups are created only when you ask for them. Deleting local data cannot be undone.',
    security: 'Security',
    securityBody:
      'Found a vulnerability? Report it through the process described in SECURITY.md in the repository. Please do not open public issues for exploitable bugs.',
    limitations: 'Known Limitations',
    limitationsBody:
      'No medical claims, no accuracy guarantee for computed values, single-device storage, Android only, possible data loss without your own backups. Full list: docs/KNOWN_LIMITATIONS.md.',
    licenses: 'Open Source & Licenses',
    licensesBody:
      'Built with open-source components (Expo, React Native, WatermelonDB and others). Third-party notices: docs/THIRD_PARTY_LICENSES.md. The project license itself has not been declared yet — see the repository.',
    about: 'About',
    aboutBody:
      'ApexFOSS 0.1.0 — local-first workout engine. Database schema v3. No accounts, no subscriptions, no ads, no telemetry.',
    localData: 'Local data',
    countExercises: 'Exercises',
    countRoutines: 'Routines',
    countSessions: 'Sessions',
    countReadiness: 'Readiness tests',
    deleteAll: 'Delete all local data',
    deleteAllBody:
      'Removes every exercise, routine, session, set log and readiness test from this device.',
    deleteAllConfirm:
      'Delete ALL local data on this device? This cannot be undone. Create a backup first if you want to keep your history.',
    deleteAllDone: 'Local data deleted',
    deleteAllFailed: 'Could not delete local data',
    reseedNote: 'Starter exercise presets may reappear on next launch — they are app content, not your data.',
  },
} as const;

export type Strings = typeof strings;
