/**
 * English dictionary — the source of truth for every user-visible string.
 * `Strings` is the shape every other locale must implement (see strings.es.ts).
 * Note: intentionally NOT `as const` so leaf types widen to `string` and a
 * translated dictionary can satisfy `Strings` without literal-type clashes.
 */
export const en = {
  common: {
    appName: 'ApexFOSS',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    add: 'Add',
    back: 'Back',
    none: 'None',
    optional: 'optional',
    loading: 'Loading…',
    retry: 'Retry',
    saving: 'Saving…',
    error: 'Something went wrong',
    create: 'Create',
    search: 'Search',
    noMatches: 'No matches',
    confirmDelete: 'Delete this item?',
    discardChanges: 'Discard unsaved changes?',
    discard: 'Discard',
    keepEditing: 'Keep editing',
    qrCode: 'QR code',
    viewAll: 'View all',
    language: 'Language',
    langEnglish: 'English',
    langSpanish: 'Spanish',
  },
  tabs: {
    home: 'Home',
    routines: 'Routines',
    train: 'Train',
    progress: 'Progress',
    more: 'More',
  },
  train: {
    title: 'Train',
    inProgress: 'Session in progress',
    resume: 'Resume workout',
    choose: 'Choose routine',
    recentRoutines: 'Recent routines',
    lastSession: 'Last session',
    repeatLast: 'Repeat last workout',
    emptyTitle: 'Ready when you are',
    emptyBody: 'Pick a routine to start logging sets, reps and rest timers.',
    emptyAction: 'Choose routine',
    noSessions: 'Completed sessions will show up here with time, sets and volume.',
    nextUpNew: 'Not trained yet',
  },
  progress: {
    title: 'Progress',
    analytics: 'Analytics',
    historySub: 'Sessions, details and comparison',
    recordsSub: 'Best sets and estimated 1RM',
    loadSub: 'Volume trends over 7 and 28 days',
    musclesSub: 'How your volume distributes across muscles',
    reportSub: 'Period summaries with volume, PRs and adherence',
    viewHistory: 'View history',
  },
more: {
    title: 'More',
    trainingTools: 'Training tools',
    dataSection: 'Data',
    preferences: 'Preferences',
    aboutSection: 'About & legal',
    languageRow: 'Language',
    exerciseRow: 'Exercise library',
    exerciseSub: 'Create and edit exercises, view substitutions',
    equipmentSub: 'Plates you own — used by the load solver',
    readinessSub: '10-second tap test baseline',
    backupSub: 'Share routines — full offline backup',
    reportSub: 'Training report with volume, PRs, adherence',
    trustSub: 'Privacy, terms, limitations, licenses',
    storageNote: 'All data stays on this device.',
    supportTitle: 'Support ApexFOSS',
    supportBody:
      'ApexFOSS is free, open-source and privacy-first. If it is useful to you, you can support its development.',
    supportSponsors: 'Support via GitHub Sponsors',
    supportPayPal: 'Support via PayPal',
    supportMercadoPago: 'Support via Mercado Pago',
  },
  reminders: {
    enableLabel: 'Remind me to train',
    hourLabel: 'Hour',
    minuteLabel: 'Minute',
    hint: 'Shows the next programmed routine at your usual time. Only when a program suggests one — never on unscheduled days.',
    permissionDenied:
      'Notifications are disabled. Enable them in system settings, then turn reminders on again.',
    today: 'Today',
    channelName: 'Training reminders',
  },
  home: {
    title: 'ApexFOSS',
    tagline: 'Local-first workout engine',
    startWorkout: 'Start workout',
    activeSession: 'Active session',
    resume: 'Resume',
    recentSessions: 'Recent sessions',
    exercises: 'Exercises',
    routines: 'Routines',
    authoring: 'Authoring',
    training: 'Training',
    today: 'Today',
    weekSection: 'This week',
    weekSessions: 'Sessions',
    weekVolume: 'Volume',
    weekTime: 'Time',
    weekTimeUnit: 'min',
    chartCaption: 'Daily volume · kg·reps',
    chartEmpty: 'Complete a session to see your daily load here.',
    currentRoutine: 'Current routine',
    lastTrained: 'Last trained',
    recent: 'Recent training',
    recentEmptyTitle: 'No training history yet',
    recentEmptyBody: 'Completed sessions appear here with duration, sets and volume.',
    tools: 'Quick tools',
    appSection: 'App',
    progressSnapshot: 'Progress snapshot',
    snapshotSub: 'Records, load trends and muscle balance',
  },
  exercises: {
    title: 'Exercises',
    search: 'Search exercises…',
    newExercise: 'New exercise',
    editTitle: 'Edit exercise',
    name: 'Name',
    nameRequired: 'Name is required',
    namePlaceholder: 'e.g. Back Squat',
    category: 'Category',
    categoryPlaceholder: 'e.g. legs',
    equipment: 'Equipment',
    equipmentPlaceholder: 'e.g. barbell',
    metrics: 'Tracked metrics',
    metricWeight: 'Weight',
    metricReps: 'Reps',
    metricDuration: 'Duration',
    metricDistance: 'Distance',
    empty: 'No exercises yet.',
    emptyAction: 'Create exercise',
    deleteConfirm: 'Delete this exercise?',
    deleteInUse: 'Exercise is referenced by routines. Delete anyway?',
    selectTitle: 'Select exercise',
    selectEmpty: 'No exercises yet. Create one from the Exercises screen.',
  },
  routines: {
    title: 'Routines',
    newRoutine: 'New routine',
    editTitle: 'Routine',
    name: 'Routine name',
    nameRequired: 'Routine name is required',
    empty: 'No routines yet.',
    emptyAction: 'Create routine',
    deleteConfirm: 'Delete this routine?',
    start: 'Start',
    blocks: 'Blocks',
    exercises: 'Exercises',
    integrityOk: 'Checks passed',
    duplicate: 'Duplicate',
    previewAction: 'Preview',
    newBlock: 'Add block',
    deleteBlock: 'Delete this block and its steps?',
    deleteStep: 'Delete this step?',
    noSteps: 'No steps yet',
    blockName: 'Block name',
    untitledRoutine: 'Untitled routine',
    saveFailed: 'Could not save routine',
    blockKind: {
      normal: 'NORMAL',
      superset: 'SUPERSET',
      contrast: 'CONTRAST',
      circuit: 'CIRCUIT',
      interval: 'INTERVAL',
    },
    blockRole: 'Block role',
    blockRoleMain: 'Main',
    blockRoleWarmup: 'Warm-up',
    blockRoleCooldown: 'Cool-down',
    rounds: 'Rounds',
    kind: 'Kind',
    steps: 'Steps',
    step: 'Step',
    addStep: 'Add step',
    exercise: 'Exercise',
    selectExercise: 'Select exercise',
    prescription: {
      title: 'Prescription',
      sets: 'Sets',
      reps: 'Reps',
      repsMin: 'Reps min',
      repsMax: 'Reps max',
      weight: 'Weight (kg)',
      duration: 'Duration (s)',
      rir: 'RIR',
      tempo: 'Tempo',
      tempoEcc: 'Ecc (s)',
      tempoPauseBottom: 'Pause bottom (s)',
      tempoCon: 'Con (s)',
      tempoPauseTop: 'Pause top (s)',
    },
    transition: {
      title: 'After this step',
      nextStep: 'Next step',
      loop: 'Loop to first step',
      nextBlock: 'Next block',
      immediate: 'IMMEDIATE',
      rest: 'REST',
      auto: 'AUTO_ADVANCE',
      delaySeconds: 'Rest (s)',
    },
  },
  programs: {
    title: 'Programs',
    subtitle: 'Order your routines into a training program.',
    create: 'Create program',
    name: 'Program name',
    nameRequired: 'Program name is required',
    empty: 'No programs yet.',
    routinesLabel: 'routines',
    rename: 'Rename program',
    delete: 'Delete program',
    deleteConfirm: 'Delete this program? Its routines stay in your list.',
    members: 'Program routines',
    noMembers: 'No routines in this program yet.',
    addRoutine: 'Add routine',
    noUnassigned: 'All routines are already in a program.',
    remove: 'Remove from program',
    notFound: 'Program not found',
    mesocycles: 'Mesocycles',
    createMesocycle: 'Add mesocycle',
    mesocycleName: 'Mesocycle name',
    noMesocycles: 'No mesocycles yet.',
    renameMesocycle: 'Rename mesocycle',
    deleteMesocycle: 'Delete mesocycle',
    deleteMesocycleConfirm: 'Delete this mesocycle? Its routines stay in the program.',
    mesocycleStage: 'Phase intent',
    stageNormal: 'Normal',
    stageDeload: 'Deload',
    noStage: 'No phase',
  },
  goals: {
    title: 'Goals',
    add: 'Add goal',
    chooseExercise: 'Choose exercise',
    targetKg: 'Target (kg)',
    targetRequired: 'Target must be a positive number',
    exists: 'This exercise already has a goal.',
    empty: 'No goals yet.',
    emptyBody: 'Set a target e1RM for an exercise and track progress toward it.',
    noData: 'No history yet',
    achieved: 'Achieved',
    delete: 'Delete goal',
    deleteConfirm: 'Delete this goal?',
  },
  body: {
    title: 'Body',
    add: 'Log measurement',
    measurementType: 'Measurement type',
    weight: 'Weight (kg)',
    waist: 'Waist (cm)',
    waistLabel: 'Waist',
    side: 'Side',
    left: 'Left',
    right: 'Right',
    atLeastOne: 'Enter a measurement value.',
    empty: 'No measurements yet.',
    emptyBody: 'Log your body measurements to see how they change over time.',
    latest: 'Latest',
    history: 'History',
    delete: 'Delete measurement',
    deleteConfirm: 'Delete this measurement?',
    bodyWeight: 'Body Weight',
    neck: 'Neck',
    chest: 'Chest',
    shoulders: 'Shoulders',
    hip: 'Hip',
    upperArm: 'Upper arm',
    forearm: 'Forearm',
    thigh: 'Thigh',
    calf: 'Calf',
  },
  templates: {
    title: 'Templates',
    subtitle: 'Start a routine from a pre-built structure.',
    fullBody: 'Full body',
    pushDay: 'Push day',
    pullDay: 'Pull day',
    legsDay: 'Legs day',
    failed: 'Could not create the routine',
  },
  workout: {
    start: 'Start workout',
    completeSet: 'COMPLETE',
    skip: 'Skip',
    undo: 'Undo',
    finish: 'Finish workout',
    set: 'Set',
    of: 'of',
    round: 'Round',
    next: 'NEXT',
    rest: 'REST',
    skipRest: 'Skip rest',
    startTimedExercise: 'Start timer',
    previous: 'Previous',
    noPrevious: 'First time',
    weight: 'kg',
    reps: 'reps',
    duration: 'time',
    distance: 'm',
    rir: 'RIR',
    sessionSaved: 'Session saved',
    discard: 'Discard session',
    discardConfirm: 'Discard this session? Logged sets will be deleted.',
    finishConfirm: 'Finish and save this session?',
    finishEarly: 'Stop early',
    finishEarlyTitle: 'Stop this session early?',
    finishEarlyBody:
      'Planned work remains. The session will be recorded as incomplete — logged sets are kept.',
    substitute: 'Substitute',
    substituteTitle: 'Substitute exercise',
    substituteBody: 'The programmed exercise stays on record. Choose what you actually performed.',
    substituteReasonLabel: 'Reason for the swap',
    activeConflict: 'An active session exists. Discard it and start a new one?',
    loadFailed: 'Could not load workout',
    emptyRoutine: 'This routine has no steps',
    startFailed: 'Could not start workout',
    block: 'Block',
    target: 'Target',
    tempo: 'Tempo',
    actual: 'Actual',
    plannedSets: 'planned sets',
    pause: 'Pause',
    resume: 'Resume',
    paused: 'Paused',
    nextUp: 'Next up',
    summary: 'Session summary',
    setsCompleted: 'Sets',
    note: 'Session note',
    notePlaceholder: 'How did it feel? Numbers, cues, PRs�?�',
    noteSaved: 'Note saved',
    skipSet: 'Skip set',
    extraSet: 'Extra set',
    dropSet: 'Drop set',
    reasonLabel: 'Reason (optional)',
    reasonLoadReduced: 'Less weight',
    reasonLoadIncreased: 'More weight',
    reasonRepsReduced: 'Fewer reps',
    reasonRepsIncreased: 'More reps',
    reasonFatigue: 'Fatigue',
    reasonPain: 'Pain or discomfort',
    reasonEquipment: 'No equipment',
    reasonTime: 'Short on time',
    reasonOther: 'Other',
  },
  timer: {
    rest: 'REST',
    autoAdvance: 'AUTO',
    preparation: 'GET READY',
    exercise: 'EXERCISE',
  },
  history: {
    title: 'History',
    empty: 'No sessions yet',
    emptyDetail: 'Completed workouts will appear here.',
    detail: 'Session',
    detailMissing: 'Session not found',
    completed: 'Completed',
    incomplete: 'Incomplete',
    completedAt: 'Completed',
    duration: 'Duration',
    volume: 'Volume',
    sets: 'Sets',
    actualPerformed: 'Actual',
    notLogged: 'Not logged',
    execModified: 'modified',
    execExtra: 'extra',
    execDrop: 'drop set',
    execSkipped: 'skipped',
    substituted: 'substituted',
    skippedSets: 'Skipped',
    adherence: 'Adherence',
    adherenceModified: 'Modified',
    adherenceExtra: 'Extra',
    adherenceDrop: 'Drop sets',
    sessionLoad: 'Session load',
    resistanceLoad: 'Resistance',
    durationWork: 'Duration work',
    compare: 'Compare with previous',
  },
  sessionEnd: {
    userStopped: 'Stopped early',
    timeConstraint: 'Short on time',
    fatigue: 'Fatigue',
    pain: 'Pain or discomfort',
    equipmentUnavailable: 'No equipment',
    interruption: 'Interrupted',
    technicalIssue: 'Technical issue',
    other: 'Other',
  },
  notes: {
    label: 'Workout note',
    exerciseLabel: 'Exercise note',
    exercisePlaceholder: 'Context for this exercise in this session…',
    placeholder: 'How did it go? Wins, pain, adjustments…',
    save: 'Save note',
    saved: 'Note saved.',
  },
  integrity: {
    title: 'Routine checks',
    ok: 'No problems found.',
    error: 'Error',
    warning: 'Warning',
    messages: {
      empty_routine: 'Routine has no blocks or steps.',
      no_work_steps: 'No work sets — the routine would finish without training work.',
      invalid_rounds: 'Block rounds must be at least 1.',
      missing_interval_spec: 'Interval block is missing valid work/rest/rounds settings.',
      orphan_transition: 'A transition points to a step that does not exist.',
      transition_cycle: 'Transitions form a loop that may never finish.',
      zero_target_sets: 'Work step has no target set count (engine assumes 1 set).',
      duplicate_step_id: 'Two steps in this block share the same id.',
    },
  },
  substitutions: {
    title: 'Substitutions',
    note: 'Similar exercises by movement, equipment and muscle mapping.',
    none: 'No similar exercises found yet.',
    reasons: {
      pattern: 'Same movement',
      equipment: 'Same equipment',
      muscles: 'Similar muscles',
      category: 'Same category',
    },
  },
  preview: {
    title: 'Routine preview',
    open: 'Preview',
    workSets: 'Work sets',
    plannedRest: 'Planned rest',
    minutes: 'min',
    blocks: 'Blocks',
    exercises: 'Exercises',
    byExercise: 'Sets by exercise',
    setsUnit: 'sets',
    how: 'Simulated step by step with the same engine that runs workouts.',
    truncated: 'Preview stopped early — the routine may loop indefinitely. Check step transitions.',
    empty: 'Nothing to preview yet — add blocks and steps first.',
  },
  compare: {
    title: 'Compare sessions',
    baseline: 'Previous',
    current: 'Selected',
    noBaseline: 'No earlier session to compare with',
    noBaselineBody: 'Comparison needs at least two completed sessions.',
    totals: 'Totals',
    volume: 'Volume',
    sets: 'Sets',
    time: 'Time',
    previous: 'Previous',
    selected: 'Selected',
    change: 'Change',
    exercises: 'Exercises',
    onlyPrevious: 'Only in previous',
    onlySelected: 'Only in selected',
    bestWeight: 'Best weight',
    bestReps: 'Most reps',
    est1rm: 'Est. 1RM (Epley)',
    noPerExerciseLoad: 'No load in either session',
    kgRepsUnit: 'kg·reps',
    secondsUnit: 's',
  },
  export: {
    title: 'Export',
    csv: 'Export CSV',
    csvHint: 'Sessions and set logs as CSV',
    json: 'Export JSON',
    jsonHint: 'Structured sessions as JSON',
    exported: 'Export ready',
    nothing: 'No completed sessions to export',
  },
  portability: {
    title: 'Portability',
    subtitle: 'Share routines and backup offline',
    exportRoutine: 'Export routine',
    exportRoutineHint: 'Share as portable JSON',
    showQr: 'Show QR',
    qrUnavailable: 'Too large for QR — use Share instead',
    importRoutine: 'Import routine',
    importRoutineHint: 'Paste portable JSON or open a deep link',
    importPasteTitle: 'Paste routine JSON',
    importPreviewTitle: 'Import preview',
    importConfirm: 'Import',
    importDone: 'Routine imported',
    importFailed: 'Import failed',
    importFromFile: 'Import from file',
    invalidRoutineFile: 'Not a valid .apexroutine file',
    createBackup: 'Create backup',
    createBackupHint: 'Full offline backup (.apexbackup JSON)',
    restoreBackup: 'Restore backup',
    restoreBackupHint: 'Paste backup JSON — replaces ALL local data',
    restoreConfirmTitle: 'Restore backup?',
    restoreConfirmBody:
      'This replaces every exercise, routine, session, and log on this device. This cannot be undone.',
    restoreConfirm: 'Restore',
    restoreDone: 'Backup restored',
    restoreFailed: 'Restore failed',
    restoreFromFile: 'Restore from file',
    invalidBackupFile: 'Not a valid .apexbackup file',
    restoreValidationOk: 'Validation passed — checksum verified',
    summarySchema: 'Schema',
    checksumMismatch: 'Checksum mismatch — the file is corrupted or was modified',
    newerVersion: 'This file comes from a newer version of ApexFOSS — update the app',
    invalidPayload: 'Invalid or corrupted payload',
    tooLarge: 'Payload too large for QR',
    matchedExercises: 'Matched exercises',
    newExercises: 'New exercises',
    blockCount: 'Blocks',
    stepCount: 'Steps',
    emptyPaste: 'Paste content is empty',
    schemeNote: 'Deep links use apexfoss://import',
    importPlaceholder: 'apexfoss://import?d=... or portable JSON',
    jsonPlaceholder: '{"format":"apexfoss-backup"}',
  },
  report: {
    title: 'Training Report',
    period: 'Period',
    period7d: 'Last 7 days',
    period28d: 'Last 28 days',
    periodAll: 'All time',
    sessions: 'Sessions',
    sessionsTotal: 'Total sessions',
    totalVolume: 'Total volume',
    avgSetsPerSession: 'Avg sets/session',
    volumeByExercise: 'Volume by exercise',
    noData: 'No data in this period',
    sets: 'sets',
    personalRecords: 'Personal records',
    prCount: 'Record events',
    noRecords: 'No records yet',
    adherence: 'Adherence',
    adherenceStatus: 'Status',
    adherence_complete: 'Complete',
    adherence_partial: 'Partial',
    adherence_none: 'None',
    planned: 'Planned',
    performed: 'Performed',
    skipped: 'Skipped',
    modified: 'Modified',
    extra: 'Extra',
    bodyMetrics: 'Body metrics',
    latestWeight: 'Latest weight',
    latestWaist: 'Latest waist',
    weightDelta: 'Weight change',
    waistDelta: 'Waist change',
    na: '—',
    entries: 'Entries',
    goals: 'Goals',
    achieved: 'Achieved',
    trends: 'e1RM trends',
    improving: 'Improving',
    declining: 'Declining',
    stable: 'Stable',
    exportCsv: 'Export CSV',
  },
  units: {
    kg: 'kg',
    seconds: 's',
    minutes: 'min',
  },
  numpad: {
    title: 'Athlete numpad',
    backspace: '⌫',
    clear: 'Clear',
    active: 'Editing',
    tapField: 'Tap a field to edit',
    modifierPrefix: 'Quick add',
  },
  tempo: {
    title: 'TEMPO',
    start: 'Start tempo',
    cancel: 'Cancel',
    restart: 'Restart',
    complete: 'Tempo complete',
    currentPhase: 'Current phase',
    ready: 'Ready',
    phases: {
      eccentric: 'ECCENTRIC',
      pauseBottom: 'BOTTOM PAUSE',
      concentric: 'CONCENTRIC',
      pauseTop: 'TOP PAUSE',
    },
    phaseDots: {
      eccentric: 'Eccentric',
      pauseBottom: 'Bottom pause',
      concentric: 'Concentric',
      pauseTop: 'Top pause',
    },
  },
  interval: {
    title: 'INTERVAL',
    ready: 'Interval ready',
    start: 'Start interval',
    cancel: 'Cancel',
    restart: 'Restart',
    skipPhase: 'Skip phase',
    finishRound: 'Finish work',
    complete: 'Interval complete',
    continue: 'Continue workout',
    round: 'Round',
    of: 'of',
    next: 'NEXT',
    modes: {
      hiit: 'HIIT',
      emom: 'EMOM',
      glycolytic: 'GLYCOLYTIC',
    },
    phases: {
      prep: 'PREP',
      work: 'WORK',
      rest: 'REST',
    },
    editor: {
      mode: 'Mode',
      work: 'Work (s)',
      rest: 'Rest (s)',
      period: 'Period (s)',
      rounds: 'Rounds',
      prep: 'Prep (s)',
      periodHint: 'EMOM period (e.g. 60)',
      workHint: '0 = full minute',
      summary: 'Summary',
    },
  },
  athleteTools: {
    section: 'Athlete tools',
    load: 'Training load',
    muscles: 'Muscle distribution',
    inventory: 'Load inventory',
    readiness: 'Readiness tap test',
    autoreg: 'RIR autoregulation',
    records: 'Personal records',
  },
  records: {
    title: 'Personal records',
    emptyTitle: 'No records yet',
    emptyBody: 'Records appear after completed sessions with logged sets.',
    weight: 'Best weight',
    reps: 'Most reps',
    est1rm: 'Est. 1RM (Epley)',
    duration: 'Longest set',
    distance: 'Farthest set',
    estimateBadge: 'Estimated',
    estimateHint: 'Estimate: weight × (1 + reps ÷ 30) — not a measured value.',
    history: 'Record history',
    recentPerformances: 'Recent performances',
    setsUnit: 'sets',
    previously: 'Previously',
    showHistory: 'Show history',
    hideHistory: 'Hide history',
    kg: 'kg',
    secUnit: 's',
    mUnit: 'm',
  },
  load: {
    title: 'Training load',
    today: 'Today',
    last7: '7 days',
    last28: '28 days',
    resistance: 'Resistance',
    duration: 'Duration',
    sets: 'Sets',
    noData: 'No completed sessions in this window',
    kgReps: 'kg·reps',
    seconds: 's',
    completedSets: 'Completed sets',
    trends: {
      section: 'Load trends',
      current7: 'Last 7 days',
      previous7: 'Previous 7 days',
      current28: 'Last 28 days',
      previous28: 'Previous 28 days',
      change: 'Change',
      noPrevious: 'No previous data',
      sessions: 'Sessions',
      load: 'Load',
    },
    ratio: {
      label: '7d / 28d load ratio',
      currentWeek: 'Current week',
      baselineWeek: 'Baseline (previous 28 days ÷ 4)',
      noBaseline: 'No baseline sessions in the previous 28 days',
      zeroBaseline: 'Baseline window has no resistance load',
    },
    rhythm: {
      section: 'Training rhythm',
      window: 'Last 7 days',
      frequency: 'Sessions / week',
      avgSets: 'Avg sets / session',
      density: 'Work / minute',
      densityUnit: 'kg·reps/min',
      weekly: 'Weekly volume',
      weeklyLabel: 'Weekly volume, last 8 weeks, kg·reps',
      weeklyCaption: 'Weekly volume · kg·reps · last 8 weeks',
      weeklyEmpty: 'Complete a session to see your weekly volume here.',
    },
  },
  muscles: {
    title: 'Muscle distribution',
    noData: 'No resistance load in this window',
    mappedLoad: 'Mapped load',
    sessions: 'Sessions',
    share: 'Share',
    sets: 'Sets',
    loadLabel: 'Load',
    exercisesLabel: 'Exercises',
    contributing: 'Contributing exercises',
    unmappedFor: 'Muscle data unavailable for',
    exerciseOne: 'exercise',
    exerciseMany: 'exercises',
    detailHint: 'Tap a region to see its detail. Timed work is not included.',
    groups: {
      chest: 'Chest',
      upper_back: 'Upper back',
      lats: 'Lats',
      front_delts: 'Front delts',
      side_delts: 'Side delts',
      rear_delts: 'Rear delts',
      biceps: 'Biceps',
      triceps: 'Triceps',
      forearms: 'Forearms',
      abs: 'Abs',
      obliques: 'Obliques',
      lower_back: 'Lower back',
      glutes: 'Glutes',
      quads: 'Quads',
      hamstrings: 'Hamstrings',
      calves: 'Calves',
      adductors: 'Adductors',
    },
  },
  inventory: {
    title: 'Load inventory',
    target: 'Target (kg)',
    bar: 'Bar (kg)',
    solve: 'Solve',
    status: {
      exact: 'Exact',
      closest: 'Closest',
      impossible: 'Cannot reach target with current inventory',
    },
    achieved: 'Achieved',
    difference: 'Difference',
    items: 'Items',
    addItem: 'Add item',
    name: 'Name',
    weight: 'Weight (kg)',
    quantity: 'Quantity',
    perSide: 'Per side (×2)',
    remove: 'Remove',
    empty: 'No items yet. Add plates or load pieces.',
    noAllocations: 'No allocations needed (target equals bar).',
    summary: 'Result',
    saved: 'Inventory saved on this device.',
    loadFailed: 'Could not load saved inventory.',
    saveFailed: 'Could not save inventory.',
  },
  readiness: {
    title: 'Readiness tap test',
    instructions: 'Tap as fast as you can for 10 seconds.',
    start: 'Start test',
    stop: 'Stop',
    tapping: 'TAP',
    elapsed: 'Elapsed',
    taps: 'Taps',
    score: 'Score',
    baseline: 'Baseline',
    deviation: 'Deviation',
    noBaseline: 'Need at least 3 prior tests before a score is shown.',
    insufficient: 'Not enough history for a baseline yet.',
    samples: 'samples',
    completed: 'Test recorded',
    failed: 'Could not record test',
    history: 'Recent tests',
    scoreUnit: '/100',
  },
  autoreg: {
    title: 'RIR autoregulation',
    enabled: 'Enabled',
    targetRir: 'Target RIR',
    step: 'Step (kg)',
    min: 'Min (kg)',
    max: 'Max (kg)',
    recommendation: 'Next set suggestion',
    hold: 'Hold',
    increase: 'Increase',
    decrease: 'Decrease',
    disabled: 'Autoregulation is off',
    noTarget: 'Set a target RIR in the prescription to enable adjustments.',
    hint: 'Adjustments apply at runtime only — routine definitions are never modified.',
  },
  progression: {
    section: 'Progression intelligence',
    cardSub: 'What is progressing, and why',
    overviewSub: 'Based on your last comparable sessions',
    stateProgress: 'Progressing',
    stateMaintain: 'Maintaining',
    stateInsufficient: 'Not enough data',
    stateProgressAnnounce: 'Progressing',
    stateMaintainAnnounce: 'Maintaining',
    stateInsufficientAnnounce: 'Not enough data',
    reason: {
      REPS_RANGE_COMPLETED: 'Reached the top of the rep range at the target weight',
      REPS_EXCEEDED_RANGE: 'Exceeded the top of the rep range at the target weight',
      REPS_BELOW_MIN: 'Reps below the prescribed minimum',
      REPS_IN_RANGE: 'Reps inside the prescribed range',
      INSUFFICIENT_HISTORY: 'Needs at least two comparable sessions',
      NO_COMPARABLE_PERFORMANCE: 'No comparable sessions for this exercise yet',
      PRESCRIPTION_MISMATCH: 'The prescription changed, so sessions are not comparable',
      NO_REPS_RANGE: 'This prescription has no rep range to progress within',
      NO_CURRENT_WEIGHT: 'No target weight recorded for this exercise',
      NO_RIR_DATA: 'RIR was not logged in the compared sessions',
      SUBSTITUTION_USED: 'Latest session used a substitute exercise',
      PREVIOUS_SUBSTITUTION: 'Earlier sessions used a substitute exercise',
      EQUIPMENT_MISMATCH: 'Equipment changed, so sessions are not comparable',
      TEMPO_MISMATCH: 'Tempo changed, so sessions are not comparable',
    },
    emptyTitle: 'No progression evidence yet',
    emptyBody:
      'Complete a few sessions with an exercise that has a rep range and target weight. ApexFOSS compares them deterministically — never guesses.',
    insufficientHint: 'Comparisons need two sessions with the same exercise, equipment and prescription scheme.',
    whyTitle: 'Why this verdict',
    comparedAgainst: 'Compared with',
    repsAchieved: 'Reps performed',
    repRange: 'Rep range',
    targetWeight: 'Target weight',
    nextWeight: 'Next load from your equipment',
    noWeightSource: 'Set your plates in Inventory to see the next load you can actually load.',
    sessionsCompared: 'Sessions compared',
    detailEmptyTitle: 'No progression analysis for this exercise',
    detailEmptyBody:
      'ApexFOSS could not compare this exercise across sessions yet. Log it in two sessions with the same prescription and equipment.',
    inventoryLink: 'Open Inventory',
  },
  signals: {
    section: 'Performance signals',
    sub: 'Deterministic trends from your logged history',
    state: {
      improving: 'Improving',
      declining: 'Declining',
      stable: 'Stable',
      insufficient_data: 'Not enough data',
    },
    reason: {
      INSUFFICIENT_HISTORY: 'Needs at least four comparable sessions',
      E1RM_STABLE: 'Best estimated 1RM held steady across recent sessions',
      E1RM_INCREASED: 'Recent sessions are above the earlier baseline',
      E1RM_DECREASED: 'Recent sessions are below the earlier baseline',
    },
  },
  trust: {
    section: 'App',
    title: 'Trust, Safety & Legal',
    privacy: 'Privacy',
    privacyBody:
      'ApexFOSS stores workouts, routines and settings only on this device. There are no accounts and no project-run servers. Exports and backups only leave the device when you share them yourself. See docs/PRIVACY.md in the repository for the full notice.',
    terms: 'Terms of Use',
    termsBody:
      'Draft pending human/legal review — see docs/TERMS_OF_USE.md. Using this software is your own responsibility; no professional relationship is created by using it.',
    health: 'Health & Fitness',
    healthBody:
      'ApexFOSS is general fitness software for recording and timing your own training. It is not medical software: it does not diagnose, treat, monitor or predict any health condition, and it does not replace professional advice. Physical activity carries risk — train within your own limits.',
    dataStorage: 'Data & Storage',
    dataBody:
      'Everything below lives in the local database on this device. Backups are created only when you ask for them. Deleting local data cannot be undone.',
    security: 'Security',
    securityBody:
      'Found a vulnerability? Report it through the process described in SECURITY.md in the repository. Please do not open public issues for exploitable bugs.',
    limitations: 'Known Limitations',
    limitationsBody:
      'No medical claims, no accuracy guarantee for computed values, single-device storage, Android only, possible data loss without your own backups. Full list: docs/KNOWN_LIMITATIONS.md.',
    licenses: 'Open Source & Licenses',
    licensesBody:
      'Built with open-source components (Expo, React Native, WatermelonDB and others). Third-party notices: docs/THIRD_PARTY_LICENSES.md. The project license itself has not been declared yet — see the repository.',
    about: 'About',
    aboutBody:
      'ApexFOSS 1.1.0 — local-first workout engine. Database schema v13. No accounts, no subscriptions, no ads, no telemetry.',
    localData: 'Local data',
    countExercises: 'Exercises',
    countRoutines: 'Routines',
    countSessions: 'Sessions',
    countReadiness: 'Readiness tests',
    deleteAll: 'Delete all local data',
    deleteAllBody:
      'Removes every training record from this device, including routines, sessions, programs, goals, equipment and body measurements.',
    deleteAllConfirm:
      'Delete ALL local data on this device? This cannot be undone. Create a backup first if you want to keep your history.',
    deleteAllDone: 'Local data deleted',
    deleteAllFailed: 'Could not delete local data',
    reseedNote: 'Starter exercise presets may reappear on next launch — they are app content, not your data.',
  },
};

export type Strings = typeof en;
