/**
 * Every user-visible string lives here (English, per approved plan).
 * No i18n framework in MVP — centralization only.
 */
export const strings = {
  common: {
    appName: 'ApexFOSS',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    add: 'Add',
    back: 'Back',
    none: 'None',
    optional: 'optional',
    loading: 'Loading…',
    retry: 'Retry',
    saving: 'Saving…',
    error: 'Something went wrong',
    create: 'Create',
    search: 'Search',
    noMatches: 'No matches',
    confirmDelete: 'Delete this item?',
  },
  tabs: {
    home: 'Home',
    routines: 'Routines',
    history: 'History',
    settings: 'Settings',
  },
  home: {
    title: 'ApexFOSS',
    tagline: 'Local-first workout engine',
    startWorkout: 'Start workout',
    activeSession: 'Active session',
    resume: 'Resume',
    recentSessions: 'Recent sessions',
    noSessions: 'No sessions yet. Create a routine and start training.',
    exercises: 'Exercises',
    routines: 'Routines',
    authoring: 'Authoring',
  },
  exercises: {
    title: 'Exercises',
    search: 'Search exercises…',
    newExercise: 'New exercise',
    editTitle: 'Edit exercise',
    name: 'Name',
    nameRequired: 'Name is required',
    namePlaceholder: 'e.g. Back Squat',
    category: 'Category',
    categoryPlaceholder: 'e.g. legs',
    equipment: 'Equipment',
    equipmentPlaceholder: 'e.g. barbell',
    metrics: 'Tracked metrics',
    metricWeight: 'Weight',
    metricReps: 'Reps',
    metricDuration: 'Duration',
    metricDistance: 'Distance',
    empty: 'No exercises yet.',
    emptyAction: 'Create exercise',
    deleteConfirm: 'Delete this exercise?',
    deleteInUse: 'Exercise is referenced by routines. Delete anyway?',
    selectTitle: 'Select exercise',
    selectEmpty: 'No exercises yet. Create one from the Exercises screen.',
  },
  routines: {
    title: 'Routines',
    newRoutine: 'New routine',
    editTitle: 'Routine',
    name: 'Routine name',
    nameRequired: 'Routine name is required',
    empty: 'No routines yet.',
    emptyAction: 'Create routine',
    deleteConfirm: 'Delete this routine?',
    blocks: 'Blocks',
    newBlock: 'Add block',
    deleteBlock: 'Delete block?',
    deleteStep: 'Delete step?',
    noSteps: 'No steps yet',
    blockName: 'Block name',
    blockKind: {
      normal: 'NORMAL',
      superset: 'SUPERSET',
      contrast: 'CONTRAST',
      circuit: 'CIRCUIT',
    },
    rounds: 'Rounds',
    steps: 'Steps',
    step: 'Step',
    addStep: 'Add step',
    exercise: 'Exercise',
    selectExercise: 'Select exercise',
    prescription: {
      title: 'Prescription',
      sets: 'Sets',
      reps: 'Reps',
      repsMin: 'Reps min',
      repsMax: 'Reps max',
      weight: 'Weight (kg)',
      duration: 'Duration (s)',
      rir: 'RIR',
      tempo: 'Tempo',
      tempoEcc: 'Ecc (s)',
      tempoPauseBottom: 'Pause bottom (s)',
      tempoCon: 'Con (s)',
      tempoPauseTop: 'Pause top (s)',
    },
    transition: {
      title: 'After this step',
      nextStep: 'Next step',
      loop: 'Loop to first step',
      nextBlock: 'Next block',
      immediate: 'IMMEDIATE',
      rest: 'REST',
      auto: 'AUTO_ADVANCE',
      delaySeconds: 'Rest (s)',
    },
  },
  workout: {
    start: 'Start workout',
    completeSet: 'COMPLETE',
    skip: 'Skip',
    undo: 'Undo',
    finish: 'Finish workout',
    set: 'Set',
    of: 'of',
    round: 'Round',
    next: 'NEXT',
    rest: 'REST',
    skipRest: 'Skip rest',
    previous: 'Previous',
    noPrevious: 'First time',
    weight: 'kg',
    reps: 'reps',
    duration: 'time',
    distance: 'm',
    rir: 'RIR',
    sessionSaved: 'Session saved',
    discard: 'Discard session',
    discardConfirm: 'Discard this session? Logged sets will be deleted.',
    finishConfirm: 'Finish and save this session?',
  },
  timer: {
    rest: 'REST',
    autoAdvance: 'AUTO',
  },
  history: {
    title: 'History',
    empty: 'No sessions yet',
    duration: 'Duration',
    volume: 'Volume',
    sets: 'Sets',
  },
  export: {
    title: 'Export',
    csv: 'Export CSV',
    csvHint: 'Sessions and set logs as CSV files',
    exported: 'Export ready',
  },
  units: {
    kg: 'kg',
    seconds: 's',
    minutes: 'min',
  },
} as const;

export type Strings = typeof strings;
