import type { Strings } from './strings.en';

/**
 * Spanish (es-AR flavored, neutral register) dictionary.
 * The `Strings` type enforces full key parity with `en` at compile time —
 * a missing key is a TypeScript error. Technical tokens (kg, RIR, 1RM,
 * EMOM, HIIT, CSV, JSON, QR, min, apexfoss://, file extensions…) stay as-is.
 */
export const es: Strings = {
  common: {
    appName: 'ApexFOSS',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    done: 'Listo',
    add: 'Agregar',
    back: 'Atrás',
    none: 'Ninguno',
    optional: 'opcional',
    loading: 'Cargando…',
    retry: 'Reintentar',
    saving: 'Guardando…',
    error: 'Algo salió mal',
    create: 'Crear',
    search: 'Buscar',
    noMatches: 'Sin coincidencias',
    confirmDelete: '¿Eliminar este elemento?',
    discardChanges: '¿Descartar los cambios sin guardar?',
    discard: 'Descartar',
    keepEditing: 'Seguir editando',
    qrCode: 'Código QR',
    viewAll: 'Ver todo',
    language: 'Idioma',
    langEnglish: 'Inglés',
    langSpanish: 'Español',
  },
  tabs: {
    home: 'Inicio',
    routines: 'Rutinas',
    train: 'Entrenar',
    progress: 'Progreso',
    more: 'Más',
  },
  train: {
    title: 'Entrenar',
    inProgress: 'Sesión en curso',
    resume: 'Reanudar entrenamiento',
    choose: 'Elegir rutina',
    recentRoutines: 'Rutinas recientes',
    lastSession: 'Última sesión',
    repeatLast: 'Repetir último entrenamiento',
    emptyTitle: 'Cuando quieras',
    emptyBody: 'Elige una rutina para empezar a registrar series, reps y descansos.',
    emptyAction: 'Elegir rutina',
    noSessions: 'Las sesiones completadas aparecerán aquí con tiempo, series y volumen.',
    nextUpNew: 'Aún sin entrenar',
  },
  progress: {
    title: 'Progreso',
    analytics: 'Analítica',
    historySub: 'Sesiones, detalles y comparación',
    recordsSub: 'Mejores series y 1RM estimado',
    loadSub: 'Tendencias de volumen a 7 y 28 días',
    musclesSub: 'Cómo se distribuye tu volumen entre los músculos',
    viewHistory: 'Ver historial',
  },
  more: {
    title: 'Más',
    trainingTools: 'Herramientas de entrenamiento',
    dataSection: 'Datos',
    preferences: 'Preferencias',
    aboutSection: 'Acerca de la app y legal',
    languageRow: 'Idioma',
    exerciseRow: 'Biblioteca de ejercicios',
    exerciseSub: 'Crear y editar ejercicios, ver sustituciones',
    equipmentSub: 'Placas que tienes — las usa el solucionador de cargas',
    readinessSub: 'Prueba de latidos de 10 segundos',
    backupSub: 'Compartir rutinas · copia de seguridad sin conexión',
    trustSub: 'Privacidad, términos, limitaciones, licencias',
    storageNote: 'Todos los datos permanecen en este dispositivo.',
  },
  home: {
    title: 'ApexFOSS',
    tagline: 'Motor de entrenamiento local',
    startWorkout: 'Iniciar entrenamiento',
    activeSession: 'Sesión activa',
    resume: 'Reanudar',
    recentSessions: 'Sesiones recientes',
    exercises: 'Ejercicios',
    routines: 'Rutinas',
    authoring: 'Edición',
    training: 'Entrenamiento',
    today: 'Hoy',
    weekSection: 'Esta semana',
    weekSessions: 'Sesiones',
    weekVolume: 'Volumen',
    weekTime: 'Tiempo',
    weekTimeUnit: 'min',
    chartCaption: 'Volumen diario · kg·reps',
    chartEmpty: 'Completa una sesión para ver tu carga diaria aquí.',
    currentRoutine: 'Rutina actual',
    lastTrained: 'Último entrenamiento',
    recent: 'Entrenamiento reciente',
    recentEmptyTitle: 'Aún no hay historial de entrenamiento',
    recentEmptyBody: 'Las sesiones completadas aparecen aquí con duración, series y volumen.',
    tools: 'Herramientas rápidas',
    appSection: 'App',
    progressSnapshot: 'Resumen de progreso',
    snapshotSub: 'Récords, tendencias de carga y equilibrio muscular',
  },
  exercises: {
    title: 'Ejercicios',
    search: 'Buscar ejercicios…',
    newExercise: 'Nuevo ejercicio',
    editTitle: 'Editar ejercicio',
    name: 'Nombre',
    nameRequired: 'El nombre es obligatorio',
    namePlaceholder: 'p. ej., Sentadilla con barra',
    category: 'Categoría',
    categoryPlaceholder: 'p. ej., piernas',
    equipment: 'Equipamiento',
    equipmentPlaceholder: 'p. ej., barra',
    metrics: 'Métricas registradas',
    metricWeight: 'Peso',
    metricReps: 'Reps',
    metricDuration: 'Duración',
    metricDistance: 'Distancia',
    empty: 'Aún no hay ejercicios.',
    emptyAction: 'Crear ejercicio',
    deleteConfirm: '¿Eliminar este ejercicio?',
    deleteInUse: 'El ejercicio está referenciado por rutinas. ¿Eliminar de todos modos?',
    selectTitle: 'Seleccionar ejercicio',
    selectEmpty: 'Aún no hay ejercicios. Crea uno desde la pantalla de Ejercicios.',
  },
  routines: {
    title: 'Rutinas',
    newRoutine: 'Nueva rutina',
    editTitle: 'Rutina',
    name: 'Nombre de la rutina',
    nameRequired: 'El nombre de la rutina es obligatorio',
    empty: 'Aún no hay rutinas.',
    emptyAction: 'Crear rutina',
    deleteConfirm: '¿Eliminar esta rutina?',
    start: 'Comenzar',
    blocks: 'Bloques',
    exercises: 'Ejercicios',
    integrityOk: 'Verificaciones OK',
    duplicate: 'Duplicada',
    previewAction: 'Previsualizar',
    newBlock: 'Agregar bloque',
    deleteBlock: '¿Eliminar este bloque y sus pasos?',
    deleteStep: '¿Eliminar este paso?',
    noSteps: 'Aún no hay pasos',
    blockName: 'Nombre del bloque',
    untitledRoutine: 'Rutina sin título',
    saveFailed: 'No se pudo guardar la rutina',
    blockKind: {
      normal: 'NORMAL',
      superset: 'SUPERSERIE',
      contrast: 'CONTRASTE',
      circuit: 'CIRCUITO',
      interval: 'INTERVALO',
    },
    rounds: 'Rondas',
    kind: 'Tipo',
    steps: 'Pasos',
    step: 'Paso',
    addStep: 'Agregar paso',
    exercise: 'Ejercicio',
    selectExercise: 'Seleccionar ejercicio',
    prescription: {
      title: 'Prescripción',
      sets: 'Series',
      reps: 'Reps',
      repsMin: 'Reps mín.',
      repsMax: 'Reps máx.',
      weight: 'Peso (kg)',
      duration: 'Duración (s)',
      rir: 'RIR',
      tempo: 'Tempo',
      tempoEcc: 'Exc (s)',
      tempoPauseBottom: 'Pausa abajo (s)',
      tempoCon: 'Conc (s)',
      tempoPauseTop: 'Pausa arriba (s)',
    },
    transition: {
      title: 'Después de este paso',
      nextStep: 'Siguiente paso',
      loop: 'Volver al primer paso',
      nextBlock: 'Siguiente bloque',
      immediate: 'INMEDIATO',
      rest: 'DESCANSO',
      auto: 'AVANCE_AUTOMÁTICO',
      delaySeconds: 'Descanso (s)',
    },
  },
  programs: {
    title: 'Programas',
    subtitle: 'Ordena tus rutinas en un programa de entrenamiento.',
    create: 'Crear programa',
    name: 'Nombre del programa',
    nameRequired: 'El nombre del programa es obligatorio',
    empty: 'Aún no hay programas.',
    routinesLabel: 'rutinas',
    rename: 'Renombrar programa',
    delete: 'Eliminar programa',
    deleteConfirm: '¿Eliminar este programa? Sus rutinas seguirán en tu lista.',
    members: 'Rutinas del programa',
    noMembers: 'Aún no hay rutinas en este programa.',
    addRoutine: 'Añadir rutina',
    noUnassigned: 'Todas las rutinas ya están en un programa.',
    remove: 'Quitar del programa',
    notFound: 'Programa no encontrado',
    mesocycles: 'Mesociclos',
    createMesocycle: 'Añadir mesociclo',
    mesocycleName: 'Nombre del mesociclo',
    noMesocycles: 'Aún no hay mesociclos.',
    renameMesocycle: 'Renombrar mesociclo',
    deleteMesocycle: 'Eliminar mesociclo',
    deleteMesocycleConfirm: '¿Eliminar este mesociclo? Sus rutinas seguirán en el programa.',
    noStage: 'Sin fase',
  },
  goals: {
    title: 'Metas',
    add: 'Agregar meta',
    chooseExercise: 'Elegir ejercicio',
    targetKg: 'Objetivo (kg)',
    targetRequired: 'El objetivo debe ser un número positivo',
    exists: 'Este ejercicio ya tiene una meta.',
    empty: 'Sin metas todavía.',
    emptyBody: 'Define un 1RM objetivo para un ejercicio y sigue el progreso hacia él.',
    noData: 'Sin historial aún',
    achieved: 'Lograda',
    delete: 'Eliminar meta',
    deleteConfirm: '¿Eliminar esta meta?',
  },
  body: {
    title: 'Cuerpo',
    add: 'Registrar medida',
    weight: 'Peso (kg)',
    waist: 'Cintura (cm)',
    atLeastOne: 'Ingresa un peso o una medida de cintura.',
    empty: 'Sin medidas todavía.',
    emptyBody: 'Registra tu peso y cintura para ver cómo cambian con el tiempo.',
    latest: 'Último',
    delete: 'Eliminar medida',
    deleteConfirm: '¿Eliminar esta medida?',
  },
  workout: {
    start: 'Iniciar entrenamiento',
    completeSet: 'COMPLETAR',
    skip: 'Omitir',
    undo: 'Deshacer',
    finish: 'Finalizar entrenamiento',
    set: 'Serie',
    of: 'de',
    round: 'Ronda',
    next: 'SIGUIENTE',
    rest: 'DESCANSO',
    skipRest: 'Omitir descanso',
    previous: 'Anterior',
    noPrevious: 'Primera vez',
    weight: 'kg',
    reps: 'reps',
    duration: 'tiempo',
    distance: 'm',
    rir: 'RIR',
    sessionSaved: 'Sesión guardada',
    discard: 'Descartar sesión',
    discardConfirm: '¿Descartar esta sesión? Las series registradas se eliminarán.',
    finishConfirm: '¿Finalizar y guardar esta sesión?',
    activeConflict: 'Ya existe una sesión activa. ¿Descartarla y empezar una nueva?',
    loadFailed: 'No se pudo cargar el entrenamiento',
    emptyRoutine: 'Esta rutina no tiene pasos',
    startFailed: 'No se pudo iniciar el entrenamiento',
    block: 'Bloque',
    target: 'Objetivo',
    tempo: 'Tempo',
    actual: 'Real',
    plannedSets: 'series planificadas',
    pause: 'Pausa',
    resume: 'Reanudar',
    paused: 'En pausa',
    nextUp: 'A continuación',
    summary: 'Resumen de la sesión',
    setsCompleted: 'Series',
    note: 'Nota de la sesión',
    notePlaceholder: '¿Cómo se sintió? Números, indicaciones, récords…',
    noteSaved: 'Nota guardada',
    skipSet: 'Omitir serie',
    extraSet: 'Serie extra',
    dropSet: 'Serie descendente',
    reasonLabel: 'Motivo (opcional)',
    reasonLoadReduced: 'Menos peso',
    reasonLoadIncreased: 'Más peso',
    reasonRepsReduced: 'Menos reps',
    reasonRepsIncreased: 'Más reps',
    reasonFatigue: 'Fatiga',
    reasonPain: 'Dolor o molestia',
    reasonEquipment: 'Sin material',
    reasonTime: 'Poco tiempo',
    reasonOther: 'Otro',
  },
  timer: {
    rest: 'DESCANSO',
    autoAdvance: 'AUTO',
  },
  history: {
    title: 'Historial',
    empty: 'Aún no hay sesiones',
    emptyDetail: 'Los entrenamientos completados aparecerán aquí.',
    detail: 'Sesión',
    detailMissing: 'Sesión no encontrada',
    completed: 'Completada',
    completedAt: 'Completada',
    duration: 'Duración',
    volume: 'Volumen',
    sets: 'Series',
    actualPerformed: 'Real',
    notLogged: 'Sin registrar',
    execModified: 'modificada',
    execExtra: 'adicional',
    execDrop: 'descendente',
    execSkipped: 'omitida',
    skippedSets: 'Omitidas',
    adherence: 'Cumplimiento',
    adherenceModified: 'Modificadas',
    adherenceExtra: 'Adicionales',
    adherenceDrop: 'Series descendentes',
    sessionLoad: 'Carga de la sesión',
    resistanceLoad: 'Resistencia',
    durationWork: 'Duración del trabajo',
    compare: 'Comparar con la anterior',
  },
  notes: {
    label: 'Nota del entrenamiento',
    placeholder: '¿Cómo salió? Logros, molestias, ajustes…',
    save: 'Guardar nota',
    saved: 'Nota guardada.',
  },
  integrity: {
    title: 'Verificaciones de la rutina',
    ok: 'No se encontraron problemas.',
    error: 'Error',
    warning: 'Advertencia',
    messages: {
      empty_routine: 'La rutina no tiene bloques ni pasos.',
      no_work_steps: 'Sin series de trabajo — la rutina terminaría sin trabajo de entrenamiento.',
      invalid_rounds: 'Las rondas del bloque deben ser al menos 1.',
      missing_interval_spec: 'Al bloque de intervalo le faltan ajustes válidos de trabajo/descanso/rondas.',
      orphan_transition: 'Una transición apunta a un paso que no existe.',
      transition_cycle: 'Las transiciones forman un ciclo que puede no terminar nunca.',
      zero_target_sets: 'El paso de trabajo no tiene cantidad objetivo de series (el motor asume 1 serie).',
      duplicate_step_id: 'Dos pasos de este bloque comparten el mismo id.',
    },
  },
  substitutions: {
    title: 'Sustituciones',
    note: 'Ejercicios similares por movimiento, equipamiento y mapeo muscular.',
    none: 'Aún no se encontraron ejercicios similares.',
    reasons: {
      pattern: 'Mismo movimiento',
      equipment: 'Mismo equipamiento',
      muscles: 'Músculos similares',
      category: 'Misma categoría',
    },
  },
  preview: {
    title: 'Vista previa de la rutina',
    open: 'Vista previa',
    workSets: 'Series de trabajo',
    plannedRest: 'Descanso planificado',
    minutes: 'min',
    blocks: 'Bloques',
    exercises: 'Ejercicios',
    byExercise: 'Series por ejercicio',
    setsUnit: 'series',
    how: 'Simulación paso a paso con el mismo motor que ejecuta los entrenamientos.',
    truncated:
      'La vista previa se detuvo antes de tiempo — la rutina puede repetirse en bucle infinito. Revisa las transiciones de los pasos.',
    empty: 'Nada que previsualizar todavía — primero agrega bloques y pasos.',
  },
  compare: {
    title: 'Comparar sesiones',
    baseline: 'Anterior',
    current: 'Seleccionada',
    noBaseline: 'No hay una sesión anterior con la que comparar',
    noBaselineBody: 'La comparación necesita al menos dos sesiones completadas.',
    totals: 'Totales',
    volume: 'Volumen',
    sets: 'Series',
    time: 'Tiempo',
    previous: 'Anterior',
    selected: 'Seleccionada',
    change: 'Cambio',
    exercises: 'Ejercicios',
    onlyPrevious: 'Solo en la anterior',
    onlySelected: 'Solo en la seleccionada',
    bestWeight: 'Mejor peso',
    bestReps: 'Más reps',
    est1rm: '1RM estimado (Epley)',
    noPerExerciseLoad: 'Sin carga en ninguna de las dos sesiones',
    kgRepsUnit: 'kg·reps',
    secondsUnit: 's',
  },
  export: {
    title: 'Exportar',
    csv: 'Exportar CSV',
    csvHint: 'Sesiones y registros de series en CSV',
    json: 'Exportar JSON',
    jsonHint: 'Sesiones estructuradas en JSON',
    exported: 'Exportación lista',
    nothing: 'No hay sesiones completadas para exportar',
  },
  portability: {
    title: 'Portabilidad',
    subtitle: 'Comparte rutinas y crea respaldos sin conexión',
    exportRoutine: 'Exportar rutina',
    exportRoutineHint: 'Compartir como JSON portable',
    showQr: 'Mostrar QR',
    qrUnavailable: 'Demasiado grande para QR — usa Compartir en su lugar',
    importRoutine: 'Importar rutina',
    importRoutineHint: 'Pega un JSON portable o abre un enlace profundo',
    importPasteTitle: 'Pegar JSON de la rutina',
    importPreviewTitle: 'Vista previa de importación',
    importConfirm: 'Importar',
    importDone: 'Rutina importada',
    importFailed: 'Error al importar',
    createBackup: 'Crear respaldo',
    createBackupHint: 'Respaldo completo sin conexión (.apexbackup JSON)',
    restoreBackup: 'Restaurar respaldo',
    restoreBackupHint: 'Pega el JSON del respaldo — reemplaza TODOS los datos locales',
    restoreConfirmTitle: '¿Restaurar respaldo?',
    restoreConfirmBody:
      'Esto reemplaza todos los ejercicios, rutinas, sesiones y registros de este dispositivo. No se puede deshacer.',
    restoreConfirm: 'Restaurar',
    restoreDone: 'Respaldo restaurado',
    restoreFailed: 'Error al restaurar',
    invalidPayload: 'Contenido inválido o corrupto',
    tooLarge: 'Contenido demasiado grande para QR',
    matchedExercises: 'Ejercicios coincidentes',
    newExercises: 'Ejercicios nuevos',
    blockCount: 'Bloques',
    stepCount: 'Pasos',
    emptyPaste: 'El contenido pegado está vacío',
    schemeNote: 'Los enlaces profundos usan apexfoss://import',
    importPlaceholder: 'apexfoss://import?d=... o JSON portable',
    jsonPlaceholder: '{"format":"apexfoss-backup"}',
  },
  units: {
    kg: 'kg',
    seconds: 's',
    minutes: 'min',
  },
  numpad: {
    title: 'Teclado numérico de atleta',
    backspace: '⌫',
    clear: 'Borrar',
    active: 'Editando',
    tapField: 'Toca un campo para editar',
    modifierPrefix: 'Agregado rápido',
  },
  tempo: {
    title: 'TEMPO',
    start: 'Iniciar tempo',
    cancel: 'Cancelar',
    restart: 'Reiniciar',
    complete: 'Tempo completado',
    currentPhase: 'Fase actual',
    ready: 'Listo',
    phases: {
      eccentric: 'EXCÉNTRICO',
      pauseBottom: 'PAUSA ABAJO',
      concentric: 'CONCÉNTRICO',
      pauseTop: 'PAUSA ARRIBA',
    },
    phaseDots: {
      eccentric: 'Excéntrico',
      pauseBottom: 'Pausa abajo',
      concentric: 'Concéntrico',
      pauseTop: 'Pausa arriba',
    },
  },
  interval: {
    title: 'INTERVALO',
    ready: 'Intervalo listo',
    start: 'Iniciar intervalo',
    cancel: 'Cancelar',
    restart: 'Reiniciar',
    skipPhase: 'Omitir fase',
    finishRound: 'Terminar trabajo',
    complete: 'Intervalo completado',
    continue: 'Continuar entrenamiento',
    round: 'Ronda',
    of: 'de',
    next: 'SIGUIENTE',
    modes: {
      hiit: 'HIIT',
      emom: 'EMOM',
      glycolytic: 'GLICOLÍTICO',
    },
    phases: {
      prep: 'PREPARACIÓN',
      work: 'TRABAJO',
      rest: 'DESCANSO',
    },
    editor: {
      mode: 'Modo',
      work: 'Trabajo (s)',
      rest: 'Descanso (s)',
      period: 'Período (s)',
      rounds: 'Rondas',
      prep: 'Preparación (s)',
      periodHint: 'Período EMOM (p. ej. 60)',
      workHint: '0 = minuto completo',
      summary: 'Resumen',
    },
  },
  athleteTools: {
    section: 'Herramientas del atleta',
    load: 'Carga de entrenamiento',
    muscles: 'Distribución muscular',
    inventory: 'Inventario de cargas',
    readiness: 'Prueba de latidos',
    autoreg: 'Autorregulación por RIR',
    records: 'Récords personales',
  },
  records: {
    title: 'Récords personales',
    emptyTitle: 'Aún no hay récords',
    emptyBody: 'Los récords aparecen después de sesiones completadas con series registradas.',
    weight: 'Mejor peso',
    reps: 'Más reps',
    est1rm: '1RM estimado (Epley)',
    duration: 'Serie más larga',
    distance: 'Serie de mayor distancia',
    estimateBadge: 'Estimado',
    estimateHint: 'Estimación: peso × (1 + reps ÷ 30) — no es un valor medido.',
    history: 'Historial de récords',
    previously: 'Anteriormente',
    showHistory: 'Mostrar historial',
    hideHistory: 'Ocultar historial',
    kg: 'kg',
    secUnit: 's',
    mUnit: 'm',
  },
  load: {
    title: 'Carga de entrenamiento',
    today: 'Hoy',
    last7: '7 días',
    last28: '28 días',
    resistance: 'Resistencia',
    duration: 'Duración',
    sets: 'Series',
    noData: 'No hay sesiones completadas en este período',
    kgReps: 'kg·reps',
    seconds: 's',
    completedSets: 'Series completadas',
    trends: {
      section: 'Tendencias de carga',
      current7: 'Últimos 7 días',
      previous7: '7 días anteriores',
      current28: 'Últimos 28 días',
      previous28: '28 días anteriores',
      change: 'Cambio',
      noPrevious: 'Sin datos previos',
      sessions: 'Sesiones',
      load: 'Carga',
    },
    ratio: {
      label: 'Relación de carga 7d / 28d',
      currentWeek: 'Semana actual',
      baselineWeek: 'Línea base (28 días anteriores ÷ 4)',
      noBaseline: 'Sin sesiones de línea base en los 28 días anteriores',
      zeroBaseline: 'La ventana de línea base no tiene carga de resistencia',
    },
    rhythm: {
      section: 'Ritmo de entrenamiento',
      window: 'Últimos 7 días',
      frequency: 'Sesiones / semana',
      avgSets: 'Series promedio / sesión',
      density: 'Trabajo / minuto',
      densityUnit: 'kg·reps/min',
      weekly: 'Volumen semanal',
      weeklyLabel: 'Volumen semanal, últimas 8 semanas, kg·reps',
      weeklyCaption: 'Volumen semanal · kg·reps · últimas 8 semanas',
      weeklyEmpty: 'Completa una sesión para ver tu volumen semanal aquí.',
    },
  },
  muscles: {
    title: 'Distribución muscular',
    noData: 'Sin carga de resistencia en este período',
    mappedLoad: 'Carga mapeada',
    sessions: 'Sesiones',
    share: 'Participación',
    sets: 'Series',
    loadLabel: 'Carga',
    exercisesLabel: 'Ejercicios',
    contributing: 'Ejercicios que contribuyen',
    unmappedFor: 'Datos musculares no disponibles para',
    exerciseOne: 'ejercicio',
    exerciseMany: 'ejercicios',
    detailHint: 'Toca una región para ver su detalle. El trabajo cronometrado no está incluido.',
    groups: {
      chest: 'Pecho',
      upper_back: 'Espalda alta',
      lats: 'Dorsales',
      front_delts: 'Deltoides anterior',
      side_delts: 'Deltoides lateral',
      rear_delts: 'Deltoides posterior',
      biceps: 'Bíceps',
      triceps: 'Tríceps',
      forearms: 'Antebrazos',
      abs: 'Abdominales',
      obliques: 'Oblicuos',
      lower_back: 'Espalda baja',
      glutes: 'Glúteos',
      quads: 'Cuádriceps',
      hamstrings: 'Isquiotibiales',
      calves: 'Pantorrillas',
      adductors: 'Aductores',
    },
  },
  inventory: {
    title: 'Inventario de cargas',
    target: 'Objetivo (kg)',
    bar: 'Barra (kg)',
    solve: 'Calcular',
    status: {
      exact: 'Exacto',
      closest: 'Más cercano',
      impossible: 'No se puede alcanzar el objetivo con el inventario actual',
    },
    achieved: 'Alcanzado',
    difference: 'Diferencia',
    items: 'Elementos',
    addItem: 'Agregar elemento',
    name: 'Nombre',
    weight: 'Peso (kg)',
    quantity: 'Cantidad',
    perSide: 'Por lado (×2)',
    remove: 'Quitar',
    empty: 'Aún no hay elementos. Agrega discos o piezas de carga.',
    noAllocations: 'No se necesitan asignaciones (el objetivo es igual a la barra).',
    summary: 'Resultado',
    saved: 'Inventario guardado en este dispositivo.',
    loadFailed: 'No se pudo cargar el inventario guardado.',
    saveFailed: 'No se pudo guardar el inventario.',
  },
  readiness: {
    title: 'Prueba de latidos',
    instructions: 'Toca lo más rápido que puedas durante 10 segundos.',
    start: 'Iniciar prueba',
    stop: 'Detener',
    tapping: 'TOCA',
    elapsed: 'Transcurrido',
    taps: 'Toques',
    score: 'Puntaje',
    baseline: 'Línea base',
    deviation: 'Desviación',
    noBaseline: 'Se necesitan al menos 3 pruebas previas para mostrar un puntaje.',
    insufficient: 'Aún no hay historial suficiente para una línea base.',
    samples: 'muestras',
    completed: 'Prueba registrada',
    failed: 'No se pudo registrar la prueba',
    history: 'Pruebas recientes',
    scoreUnit: '/100',
  },
  autoreg: {
    title: 'Autorregulación por RIR',
    enabled: 'Activada',
    targetRir: 'RIR objetivo',
    step: 'Paso (kg)',
    min: 'Mín (kg)',
    max: 'Máx (kg)',
    recommendation: 'Sugerencia para la siguiente serie',
    hold: 'Mantener',
    increase: 'Aumentar',
    decrease: 'Disminuir',
    disabled: 'La autorregulación está desactivada',
    noTarget: 'Define un RIR objetivo en la prescripción para habilitar los ajustes.',
    hint: 'Los ajustes se aplican solo en tiempo de ejecución — las definiciones de rutina nunca se modifican.',
  },
  progression: {
    section: 'Inteligencia de progresión',
    cardSub: 'Qué progresa, y por qué',
    overviewSub: 'Según tus últimas sesiones comparables',
    stateProgress: 'Progresando',
    stateMaintain: 'Manteniendo',
    stateInsufficient: 'Faltan datos',
    stateProgressAnnounce: 'Progresando',
    stateMaintainAnnounce: 'Manteniendo',
    stateInsufficientAnnounce: 'Faltan datos',
    reason: {
      REPS_RANGE_COMPLETED: 'Alcanzó el tope del rango de repeticiones con el peso objetivo',
      REPS_EXCEEDED_RANGE: 'Superó el tope del rango de repeticiones con el peso objetivo',
      REPS_BELOW_MIN: 'Repeticiones por debajo del mínimo prescrito',
      REPS_IN_RANGE: 'Repeticiones dentro del rango prescrito',
      INSUFFICIENT_HISTORY: 'Necesita al menos dos sesiones comparables',
      NO_COMPARABLE_PERFORMANCE: 'Todavía no hay sesiones comparables para este ejercicio',
      PRESCRIPTION_MISMATCH: 'La prescripción cambió, así que las sesiones no son comparables',
      NO_REPS_RANGE: 'Esta prescripción no tiene rango de repeticiones para progresar',
      NO_CURRENT_WEIGHT: 'No hay peso objetivo registrado para este ejercicio',
      NO_RIR_DATA: 'El RIR no se registró en las sesiones comparadas',
      SUBSTITUTION_USED: 'La última sesión usó un ejercicio sustituto',
      PREVIOUS_SUBSTITUTION: 'Las sesiones anteriores usaron un ejercicio sustituto',
      EQUIPMENT_MISMATCH: 'El equipamiento cambió, así que las sesiones no son comparables',
      TEMPO_MISMATCH: 'El tempo cambió, así que las sesiones no son comparables',
    },
    emptyTitle: 'Aún no hay evidencia de progresión',
    emptyBody:
      'Completa algunas sesiones con un ejercicio que tenga rango de repeticiones y peso objetivo. ApexFOSS las compara de forma determinista — nunca adivina.',
    insufficientHint: 'Las comparaciones necesitan dos sesiones con el mismo ejercicio, equipamiento y esquema de prescripción.',
    whyTitle: 'Por qué este veredicto',
    comparedAgainst: 'Comparado con',
    repsAchieved: 'Repeticiones realizadas',
    repRange: 'Rango de repeticiones',
    targetWeight: 'Peso objetivo',
    nextWeight: 'Próxima carga con tu equipamiento',
    noWeightSource: 'Registra tus discos en Inventario para ver la próxima carga disponible.',
    sessionsCompared: 'Sesiones comparadas',
    detailEmptyTitle: 'Sin análisis de progresión para este ejercicio',
    detailEmptyBody:
      'ApexFOSS todavía no pudo comparar este ejercicio entre sesiones. Regístralo en dos sesiones con la misma prescripción y equipamiento.',
    inventoryLink: 'Abrir Inventario',
  },
  signals: {
    section: 'Señales de rendimiento',
    sub: 'Tendencias deterministas de tu historial',
    state: {
      improving: 'Mejorando',
      declining: 'Bajando',
      stable: 'Estable',
      insufficient_data: 'Datos insuficientes',
    },
    reason: {
      INSUFFICIENT_HISTORY: 'Se necesitan al menos cuatro sesiones comparables',
      E1RM_STABLE: 'El mejor 1RM estimado se mantuvo estable en las sesiones recientes',
      E1RM_INCREASED: 'Las sesiones recientes superan la línea base anterior',
      E1RM_DECREASED: 'Las sesiones recientes están por debajo de la línea base anterior',
    },
  },
  trust: {
    section: 'App',
    title: 'Centro de confianza, seguridad y legal',
    privacy: 'Privacidad',
    privacyBody:
      'ApexFOSS guarda entrenamientos, rutinas y ajustes solo en este dispositivo. No hay cuentas ni servidores del proyecto. Las exportaciones y respaldos solo salen del dispositivo cuando tú los compartes. Consulta docs/PRIVACY.md en el repositorio para el aviso completo.',
    terms: 'Términos de uso',
    termsBody:
      'Borrador pendiente de revisión humana/legal — ver docs/TERMS_OF_USE.md. Usar este software es de tu propia responsabilidad; no se crea ninguna relación profesional por usarlo.',
    health: 'Salud y forma física',
    healthBody:
      'ApexFOSS es software de fitness general para registrar y cronometrar tu propio entrenamiento. No es software médico: no diagnostica, trata, monitorea ni predice ninguna condición de salud, y no reemplaza el consejo profesional. La actividad física conlleva riesgos — entrena dentro de tus propios límites.',
    dataStorage: 'Datos y almacenamiento',
    dataBody:
      'Todo lo de abajo vive en la base de datos local de este dispositivo. Los respaldos se crean solo cuando tú lo solicitas. Eliminar los datos locales no se puede deshacer.',
    security: 'Seguridad',
    securityBody:
      '¿Encontraste una vulnerabilidad? Repórtala mediante el proceso descrito en SECURITY.md en el repositorio. Por favor no abras issues públicos para errores explotables.',
    limitations: 'Limitaciones conocidas',
    limitationsBody:
      'Sin afirmaciones médicas, sin garantía de exactitud para los valores calculados, almacenamiento en un solo dispositivo, solo Android, posible pérdida de datos sin tus propios respaldos. Lista completa: docs/KNOWN_LIMITATIONS.md.',
    licenses: 'Código abierto y licencias',
    licensesBody:
      'Construido con componentes de código abierto (Expo, React Native, WatermelonDB y otros). Avisos de terceros: docs/THIRD_PARTY_LICENSES.md. La licencia del proyecto aún no se ha declarado — ver el repositorio.',
    about: 'Acerca de',
    aboutBody:
      'ApexFOSS 0.1.0 — motor de entrenamiento local. Esquema de base de datos v6. Sin cuentas, sin suscripciones, sin anuncios, sin telemetría.',
    localData: 'Datos locales',
    countExercises: 'Ejercicios',
    countRoutines: 'Rutinas',
    countSessions: 'Sesiones',
    countReadiness: 'Pruebas de latidos',
    deleteAll: 'Eliminar todos los datos locales',
    deleteAllBody:
      'Elimina todos los ejercicios, rutinas, sesiones, registros de series y pruebas de latidos de este dispositivo.',
    deleteAllConfirm:
      '¿Eliminar TODOS los datos locales de este dispositivo? Esto no se puede deshacer. Crea un respaldo primero si quieres conservar tu historial.',
    deleteAllDone: 'Datos locales eliminados',
    deleteAllFailed: 'No se pudo eliminar los datos locales',
    reseedNote: 'Los ejercicios predefinidos pueden reaparecer en el próximo inicio — son contenido de la app, no tus datos.',
  },
};
